# Generated by Django 3.0.8 on 2021-03-08 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('designation', models.CharField(max_length=50, null=True, verbose_name='Designation')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CEO'), (2, 'Manager'), (3, 'BDE')], null=True)),
                ('department', models.CharField(max_length=50, null=True, verbose_name='Department')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
